### ISSUE TITLE
Update checklist 2024

### ISSUE THREAD

**Issue by sannegovaert** [trias-project/alien-herpetofauna-belgium#22]
We will release a new publication. Can you check wether the current checklist is up to date? @timadriaens

Most important is to check:
- [x] update `degree of establishment`
- [x] update `date last observation`
- [x] add `date first observation`. If this is missing, it will not be acocunted for in the indicator `Number of new introductions of alien species per year`. So avoiding NA's in this column is important.
- [x] add new species
- [x] `Gekkota spec (Cuvier, 1817)` does not appear on the unified checklist because infraorders are not used by the GBIF backbone taxonomy and thus not recognized. See #11

**Comment by sannegovaert** [comment]
Updated in [commit 454651f](https://github.com/trias-project/alien-herpetofauna-belgium/commit/454651f1c02f3d930c16778317c4407c5dfd0c4e).
